// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #KubeInput is the `kube` verb's plugin_input: the method name plus its
// method-exclusive modifiers.
type KubeInput struct {
	// method — the kube method name (the former core #KubeMethod enum plus the
	// internal k3s-post-provision the host synthesizes; the verb's PRIMARY input
	// field, so `kube: nodes` desugars to {method: "nodes"}).
	Method string `yaml:"method,omitempty" json:"method"`

	// name / namespace / label — resource identity + selector.
	Name string `yaml:"name,omitempty" json:"name,omitempty"`

	Namespace string `yaml:"namespace,omitempty" json:"namespace,omitempty"`

	Label string `yaml:"label,omitempty" json:"label,omitempty"`

	// cluster — a kind:kubernetes cluster template name; this PLUGIN self-resolves it to a
	// concrete kube_context (self-loading the project, K-wave W3a A3-phase-2) and
	// leaves the authored key in place, so the input def admits both.
	Cluster string `yaml:"cluster,omitempty" json:"cluster,omitempty"`

	// manifest — the multi-doc YAML path (apply/delete).
	Manifest string `yaml:"manifest,omitempty" json:"manifest,omitempty"`

	// kube_kind / kube_count — wait-ready's workload kind + wait-nodes' Ready count.
	KubeKind string `yaml:"kube_kind,omitempty" json:"kube_kind,omitempty"`

	KubeCount int `yaml:"kube_count,omitempty" json:"kube_count,omitempty"`

	// kubeconfig / kube_context — the cluster-selection pair (kubeconfig path +
	// context) an authored step may set explicitly.
	Kubeconfig string `yaml:"kubeconfig,omitempty" json:"kubeconfig,omitempty"`

	KubeContext string `yaml:"kube_context,omitempty" json:"kube_context,omitempty"`

	// kube_resource / kube_group / kube_version / json — the raw escape hatch's
	// GVR + JSON output toggle.
	KubeResource string `yaml:"kube_resource,omitempty" json:"kube_resource,omitempty"`

	KubeGroup string `yaml:"kube_group,omitempty" json:"kube_group,omitempty"`

	KubeVersion string `yaml:"kube_version,omitempty" json:"kube_version,omitempty"`

	JSON bool `yaml:"json,omitempty" json:"json,omitempty"`

	// artifact_key / deploy_name / vm_entity — the k3s-post-provision payload (S3, FINAL/K5 unit
	// 6; re-split by task #18): artifact_key is now the per-deploy DOMAIN-scoped identity (the
	// artifact cache dir + kubeconfig context — collision-free per bed, since several beds may
	// share one kind:vm entity); deploy_name is the real per-deploy identity the guest-forward
	// port-forward LEDGER lookup keys off (the same value domain-scopes artifact_key); vm_entity
	// is the SHARED kind:vm entity name (e.g. several beds' common `from: k3s-vm`), a DIFFERENT
	// identity space needed only to resolve the entity's DECLARED network.port_forwards
	// template. See this plugin's own k3s_post.go (deployVMForwards) — the former
	// charly/k8s_plugin.go core seam is deleted.
	ArtifactKey string `yaml:"artifact_key,omitempty" json:"artifact_key,omitempty"`

	DeployName string `yaml:"deploy_name,omitempty" json:"deploy_name,omitempty"`

	VmEntity string `yaml:"vm_entity,omitempty" json:"vm_entity,omitempty"`
}
